# Generated by Django 6.0.5 on 2026-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_type',
            field=models.CharField(default='Permanent', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Idle', 'Idle')], default='Active', max_length=20),
        ),
    ]
